export interface Category {
  slug: string;
  summary: string;
}

// Summaries are consumed by the app's overseer during stage-A team selection.
export const CATEGORIES: Category[] = [
  { slug: 'engineering', summary: 'Software engineering across languages, platforms, and layers' },
  { slug: 'data-ai', summary: 'Data engineering, analytics, ML, and AI systems' },
  { slug: 'security', summary: 'Offensive, defensive, and governance security' },
  { slug: 'infrastructure-devops', summary: 'Cloud, platform, SRE, networking, and release' },
  { slug: 'design', summary: 'Product, visual, brand, motion, and industrial design' },
  { slug: 'product', summary: 'Product management, research, and product analytics' },
  { slug: 'marketing', summary: 'Brand, growth, content, performance, and lifecycle marketing' },
  { slug: 'sales', summary: 'Prospecting, closing, partnerships, and revenue operations' },
  { slug: 'legal', summary: 'Transactional, litigation, regulatory, and IP practice' },
  { slug: 'finance', summary: 'Accounting, FP&A, treasury, tax, and investment' },
  { slug: 'hr-people', summary: 'Recruiting, HR ops, L&D, compensation, employee relations' },
  { slug: 'operations', summary: 'Business operations, program management, quality, process' },
  { slug: 'customer-support', summary: 'Support, success, onboarding, and escalations' },
  { slug: 'healthcare', summary: 'Clinical, allied health, veterinary, diagnostics, and health administration' },
  { slug: 'science-research', summary: 'Physical, life, earth, and social sciences research' },
  { slug: 'education', summary: 'Teaching, curriculum, instructional design, and administration' },
  { slug: 'media-content', summary: 'Writing, editing, journalism, publishing, and localization' },
  { slug: 'skilled-trades', summary: 'Electrical, plumbing, welding, HVAC, machining, and repair' },
  { slug: 'construction-realestate', summary: 'Building, surveying, estimating, and property' },
  { slug: 'hospitality-food', summary: 'Culinary, beverage, lodging, events, and service' },
  { slug: 'transport-logistics', summary: 'Freight, fleet, warehousing, customs, and transit' },
  { slug: 'public-sector', summary: 'Government, policy, emergency services, and nonprofit' },
  { slug: 'energy-environment', summary: 'Power, renewables, extraction, and environmental work' },
  { slug: 'agriculture', summary: 'Crops, livestock, forestry, fisheries, and agtech' },
  { slug: 'arts-entertainment', summary: 'Performing arts, film, music, galleries, and game narrative' },
  { slug: 'cardiology-vascular', summary: 'Heart, vascular, electrophysiology and cardiac procedures' },
  { slug: 'oncology', summary: 'Medical, radiation and surgical cancer care' },
  { slug: 'neurology-neurosurgery', summary: 'Brain, spine and nervous-system care' },
  { slug: 'orthopedics-musculoskeletal', summary: 'Bones, joints, spine and sports injuries' },
  { slug: 'obstetrics-womens-health', summary: 'Pregnancy, birth, gynecology and fertility' },
  { slug: 'pediatric-specialties', summary: 'Subspecialty care for infants, children and adolescents' },
  { slug: 'behavioral-health', summary: 'Psychiatry, therapy, addiction and crisis services' },
  { slug: 'dental-specialties', summary: 'Periodontics, endodontics, oral surgery and dental labs' },
  { slug: 'eye-and-ear-care', summary: 'Ophthalmology, optometry, ENT and hearing' },
  { slug: 'emergency-critical-care', summary: 'ED, ICU, trauma and prehospital critical care' },
  { slug: 'surgical-services', summary: 'Operating room, perioperative and surgical specialties' },
  { slug: 'rehabilitation-therapy', summary: 'PT, OT, speech, prosthetics and recovery care' },
  { slug: 'medical-imaging', summary: 'Radiology modalities, nuclear medicine and imaging physics' },
  { slug: 'laboratory-medicine', summary: 'Clinical labs, blood banking, pathology and cytology' },
  { slug: 'pharmacy-practice', summary: 'Hospital, retail, specialty and compounding pharmacy' },
  { slug: 'nursing-specialties', summary: 'Specialty, advanced-practice and unit-based nursing' },
  { slug: 'internal-medicine-specialties', summary: 'Endocrine, GI, kidney, lung, rheumatology and infectious disease' },
  { slug: 'dermatology-plastic-surgery', summary: 'Skin, aesthetic and reconstructive care' },
  { slug: 'senior-long-term-care', summary: 'Nursing homes, assisted living and geriatric care' },
  { slug: 'home-health-hospice', summary: 'Home-based, palliative and end-of-life care' },
  { slug: 'nutrition-dietetics', summary: 'Clinical nutrition, food service dietetics and feeding' },
  { slug: 'genetics-precision-medicine', summary: 'Genetic counseling, genomics and targeted therapy' },
  { slug: 'public-health', summary: 'Epidemiology, disease control and population health' },
  { slug: 'health-informatics', summary: 'EHR, clinical data, interoperability and health IT' },
  { slug: 'revenue-cycle', summary: 'Patient access, coding, billing and payer contracting' },
  { slug: 'hospital-operations', summary: 'Bed flow, patient safety, credentialing and accreditation' },
  { slug: 'health-insurance-payers', summary: 'Health plan medical management, claims and network' },
  { slug: 'veterinary-specialties', summary: 'Animal specialty, shelter, lab and zoo medicine' },
  { slug: 'drug-discovery', summary: 'Target identification, medicinal chemistry and pharmacology' },
  { slug: 'clinical-trials', summary: 'Trial design, operations, monitoring and data management' },
  { slug: 'biomanufacturing', summary: 'Cell culture, fermentation, purification and fill-finish' },
  { slug: 'medical-devices', summary: 'Device design, verification, sterilization and field service' },
  { slug: 'regulatory-affairs', summary: 'Submissions, labeling and post-market obligations' },
  { slug: 'pharma-quality', summary: 'GMP quality, validation and batch release' },
  { slug: 'pharma-commercial', summary: 'Market access, medical affairs and HEOR' },
  { slug: 'retail-banking', summary: 'Branches, deposits, consumer lending and cards' },
  { slug: 'commercial-banking', summary: 'Business lending, treasury services and credit' },
  { slug: 'mortgage-lending', summary: 'Origination, processing, underwriting and servicing' },
  { slug: 'payments', summary: 'Card networks, acquiring, ACH, real-time payments and fraud' },
  { slug: 'credit-risk-collections', summary: 'Credit risk models, recoveries and collections' },
  { slug: 'financial-crime-compliance', summary: 'AML, sanctions, KYC and investigations' },
  { slug: 'bank-operations', summary: 'Reconciliation, wires, lockbox and branch back office' },
  { slug: 'investment-banking', summary: 'M&A advisory, ECM, DCM and restructuring' },
  { slug: 'sales-and-trading', summary: 'Equities, fixed income, FX and derivatives desks' },
  { slug: 'asset-management', summary: 'Portfolio management, research and fund operations' },
  { slug: 'wealth-management', summary: 'Advisors, trusts, estate planning and family offices' },
  { slug: 'private-equity-venture', summary: 'Deal sourcing, diligence, portfolio ops and fundraising' },
  { slug: 'hedge-funds-quant', summary: 'Systematic strategies, risk and fund operations' },
  { slug: 'market-infrastructure', summary: 'Exchanges, clearing, custody and settlement' },
  { slug: 'digital-assets', summary: 'Crypto custody, trading, protocol and compliance' },
  { slug: 'pc-underwriting', summary: 'Property, casualty and specialty underwriting' },
  { slug: 'insurance-claims', summary: 'Claims adjusting, investigation, SIU and subrogation' },
  { slug: 'life-annuities', summary: 'Life, annuity and retirement product operations' },
  { slug: 'reinsurance-catastrophe', summary: 'Reinsurance, cat modeling and capital' },
  { slug: 'insurance-distribution', summary: 'Agencies, brokers, MGAs and producer management' },
  { slug: 'public-accounting', summary: 'Audit, assurance and advisory practice' },
  { slug: 'tax-practice', summary: 'Corporate, individual, international and indirect tax' },
  { slug: 'management-consulting', summary: 'Strategy, operations and transformation consulting' },
  { slug: 'corporate-development', summary: 'M&A, integration and strategic partnerships' },
  { slug: 'enterprise-risk-grc', summary: 'Enterprise risk, internal audit, controls and governance' },
  { slug: 'corporate-communications', summary: 'PR, investor relations, crisis and executive comms' },
  { slug: 'executive-leadership', summary: 'C-suite, board and general-management roles' },
  { slug: 'small-business-ownership', summary: 'Owner-operators, franchisees and startup founders' },
  { slug: 'litigation', summary: 'Trial, appellate, discovery and dispute practice' },
  { slug: 'corporate-law', summary: 'M&A, securities, governance and finance law' },
  { slug: 'intellectual-property-law', summary: 'Patents, trademarks, copyright and trade secrets' },
  { slug: 'criminal-law', summary: 'Prosecution, defense and criminal justice practice' },
  { slug: 'family-estate-law', summary: 'Family, elder, trusts and estates practice' },
  { slug: 'employment-labor-law', summary: 'Employment, benefits and labor relations law' },
  { slug: 'regulatory-administrative-law', summary: 'Agency, energy, telecom, health and environmental law' },
  { slug: 'courts-judiciary', summary: 'Judges, court administration and court services' },
  { slug: 'legal-operations-support', summary: 'Paralegals, e-discovery, litigation support and legal tech' },
  { slug: 'law-enforcement', summary: 'Patrol, investigations, forensics and specialized units' },
  { slug: 'fire-rescue', summary: 'Firefighting, rescue, fire prevention and investigation' },
  { slug: 'emergency-management', summary: 'Preparedness, response, recovery and hazard mitigation' },
  { slug: 'corrections-probation', summary: 'Custody, reentry, probation and parole' },
  { slug: 'military-operations', summary: 'Command, operations, logistics and military specialties' },
  { slug: 'defense-acquisition', summary: 'Defense programs, contracting and test and evaluation' },
  { slug: 'intelligence-analysis', summary: 'All-source, geospatial and open-source analysis' },
  { slug: 'diplomacy-international', summary: 'Foreign service, treaties and international organizations' },
  { slug: 'legislative-policy', summary: 'Legislatures, policy analysis and government affairs' },
  { slug: 'urban-regional-planning', summary: 'Land use, zoning, transportation and housing planning' },
  { slug: 'social-services', summary: 'Case management, benefits, child welfare and housing aid' },
  { slug: 'tax-administration', summary: 'Revenue agencies, audit, assessment and collection' },
  { slug: 'public-utilities-works', summary: 'Municipal utilities, streets, fleets and public works' },
  { slug: 'parks-recreation', summary: 'Parks, recreation programs and public lands' },
  { slug: 'mechanical-engineering', summary: 'Machine design, thermal, fluids and product engineering' },
  { slug: 'electrical-engineering', summary: 'Power, controls, electronics and instrumentation' },
  { slug: 'structural-engineering', summary: 'Buildings, bridges, foundations and special structures' },
  { slug: 'chemical-process-engineering', summary: 'Process design, reaction, separation and safety' },
  { slug: 'aerospace-engineering', summary: 'Aircraft, spacecraft, propulsion and flight systems' },
  { slug: 'biomedical-engineering', summary: 'Clinical engineering, biomaterials and medical instrumentation' },
  { slug: 'industrial-systems-engineering', summary: 'Systems engineering, ergonomics, operations research' },
  { slug: 'materials-engineering', summary: 'Metallurgy, polymers, ceramics and failure analysis' },
  { slug: 'environmental-engineering', summary: 'Water, air, soil and waste engineering' },
  { slug: 'nuclear-engineering', summary: 'Reactor, radiation, fuel cycle and nuclear safety' },
  { slug: 'marine-naval-engineering', summary: 'Ships, offshore structures and marine systems' },
  { slug: 'geotechnical-engineering', summary: 'Soils, rock, slopes, tunnels and earthworks' },
  { slug: 'rf-wireless-engineering', summary: 'Antennas, RF design, spectrum and wireless systems' },
  { slug: 'semiconductor-engineering', summary: 'Chip design, verification, process and yield' },
  { slug: 'robotics-automation', summary: 'Industrial robots, PLCs, motion and machine vision' },
  { slug: 'building-systems-engineering', summary: 'MEP, fire protection, energy modeling and commissioning' },
  { slug: 'reliability-test-engineering', summary: 'Reliability, test, failure analysis and qualification' },
  { slug: 'transportation-engineering', summary: 'Traffic, highway, transit and pavement engineering' },
  { slug: 'surveying-geospatial', summary: 'Surveying, GIS, remote sensing and mapping' },
  { slug: 'manufacturing-operations', summary: 'Plant management, production planning and lean' },
  { slug: 'manufacturing-quality', summary: 'Quality engineering, metrology, SPC and audits' },
  { slug: 'plant-maintenance', summary: 'Reliability, maintenance planning and industrial repair' },
  { slug: 'metals-fabrication', summary: 'Machining, forming, casting, welding and finishing' },
  { slug: 'plastics-composites', summary: 'Molding, extrusion, composites and tooling' },
  { slug: 'electronics-manufacturing', summary: 'PCB assembly, SMT, test and electronics repair' },
  { slug: 'food-beverage-manufacturing', summary: 'Food processing, brewing, bottling and food science' },
  { slug: 'textiles-apparel-production', summary: 'Textile mills, sewing, patternmaking and apparel sourcing' },
  { slug: 'printing-packaging', summary: 'Print production, converting and packaging engineering' },
  { slug: 'chemicals-manufacturing', summary: 'Specialty and bulk chemicals, coatings and formulation' },
  { slug: 'automotive-manufacturing', summary: 'Vehicle assembly, body, paint and powertrain plants' },
  { slug: 'aerospace-manufacturing', summary: 'Aircraft production, MRO, NDT and certification' },
  { slug: 'wood-products-furniture', summary: 'Sawmills, millwork, cabinetry and furniture production' },
  { slug: 'additive-manufacturing', summary: '3D printing process, design for AM and qualification' },
  { slug: 'enterprise-applications', summary: 'ERP, CRM and business-application administration' },
  { slug: 'game-development', summary: 'Game production, design, art, audio and live ops' },
  { slug: 'xr-spatial-computing', summary: 'AR, VR and spatial computing development' },
  { slug: 'it-end-user-services', summary: 'Desktop, endpoints, collaboration tools and IT support' },
  { slug: 'telecom-networks', summary: 'Carrier networks, fiber, mobile core and field ops' },
  { slug: 'space-satellite-systems', summary: 'Satellite ops, ground stations and mission control' },
  { slug: 'quantum-computing', summary: 'Quantum hardware, algorithms and quantum software' },
  { slug: 'oil-gas-upstream', summary: 'Exploration, drilling, completions and production' },
  { slug: 'oil-gas-midstream-downstream', summary: 'Pipelines, refining, petrochemicals and fuel marketing' },
  { slug: 'power-generation', summary: 'Thermal, hydro and gas-turbine plant operations' },
  { slug: 'electric-grid', summary: 'Transmission, distribution, grid operations and planning' },
  { slug: 'solar-energy', summary: 'Utility, commercial and residential solar' },
  { slug: 'wind-energy', summary: 'Onshore and offshore wind development and operations' },
  { slug: 'nuclear-power', summary: 'Nuclear plant operations, radiation protection and outage' },
  { slug: 'energy-storage-hydrogen', summary: 'Batteries, hydrogen, fuel cells and emerging energy' },
  { slug: 'energy-markets-trading', summary: 'Power and gas trading, scheduling and market analysis' },
  { slug: 'mining', summary: 'Exploration geology, mine planning and mineral processing' },
  { slug: 'water-utilities', summary: 'Drinking water, wastewater and water resources' },
  { slug: 'waste-recycling', summary: 'Solid waste, recycling, hazardous waste and landfill' },
  { slug: 'environmental-consulting', summary: 'Site assessment, permitting, remediation and compliance' },
  { slug: 'climate-sustainability', summary: 'Carbon accounting, ESG, climate risk and adaptation' },
  { slug: 'forestry-timber', summary: 'Forest management, timber harvest and wildland fire' },
  { slug: 'flight-operations', summary: 'Pilots, flight crews, dispatch and flight standards' },
  { slug: 'aircraft-maintenance', summary: 'Airframe and powerplant, avionics and MRO planning' },
  { slug: 'airport-management', summary: 'Airside, terminal, security and airport planning' },
  { slug: 'maritime-shipping', summary: 'Deck, engine, chartering and ship management' },
  { slug: 'ports-terminals', summary: 'Terminal operations, stevedoring and port authority' },
  { slug: 'railroads', summary: 'Train operations, track, signals and rail planning' },
  { slug: 'trucking-freight', summary: 'Carriers, brokerage, fleet safety and dispatch' },
  { slug: 'public-transit', summary: 'Bus, rail transit, paratransit and transit planning' },
  { slug: 'space-launch', summary: 'Launch vehicles, range operations and mission assurance' },
  { slug: 'warehousing-fulfillment', summary: 'DC operations, inventory, WMS and fulfillment' },
  { slug: 'supply-chain-planning', summary: 'Demand, supply, S&OP and network design' },
  { slug: 'procurement', summary: 'Sourcing, category management and supplier management' },
  { slug: 'international-trade', summary: 'Customs, trade compliance, freight forwarding and export' },
  { slug: 'last-mile-delivery', summary: 'Parcel, courier, routing and delivery operations' },
  { slug: 'cold-chain-logistics', summary: 'Temperature-controlled storage and transport' },
  { slug: 'retail-store-operations', summary: 'Store management, loss prevention and visual merchandising' },
  { slug: 'ecommerce-operations', summary: 'Marketplaces, catalog, site merchandising and DTC ops' },
  { slug: 'merchandising-buying', summary: 'Buying, planning, allocation and assortment' },
  { slug: 'consumer-packaged-goods', summary: 'Brand management, trade marketing and CPG sales' },
  { slug: 'fashion-apparel', summary: 'Fashion design, product development and fashion retail' },
  { slug: 'beauty-personal-care', summary: 'Cosmetic chemistry, beauty retail and salon services' },
  { slug: 'grocery-food-retail', summary: 'Grocery operations, perishables and category management' },
  { slug: 'automotive-retail-service', summary: 'Dealerships, service departments, parts and collision' },
  { slug: 'luxury-jewelry', summary: 'Jewelry, watches, gemology and luxury clienteling' },
  { slug: 'franchising', summary: 'Franchise development, field operations and compliance' },
  { slug: 'hotels-lodging', summary: 'Hotel operations, revenue, rooms and resort management' },
  { slug: 'travel-tourism', summary: 'Tour operations, travel agencies and destination management' },
  { slug: 'events-conventions', summary: 'Conferences, trade shows, weddings and venues' },
  { slug: 'fitness-wellness', summary: 'Training, coaching, spas and wellness programs' },
  { slug: 'professional-sports', summary: 'Teams, leagues, athlete performance and sports business' },
  { slug: 'gaming-casinos', summary: 'Casino operations, gaming compliance and surveillance' },
  { slug: 'cruise-attractions', summary: 'Cruise lines, theme parks and attractions' },
  { slug: 'real-estate-brokerage', summary: 'Residential and commercial brokerage and appraisal' },
  { slug: 'property-management', summary: 'Residential, commercial and association management' },
  { slug: 'real-estate-development', summary: 'Development, acquisitions and asset management' },
  { slug: 'facilities-management', summary: 'Facility operations, workplace services and FM' },
  { slug: 'home-services', summary: 'Pest, pool, locksmith, cleaning and home repair businesses' },
  { slug: 'landscaping-grounds', summary: 'Landscape design, arboriculture and turf management' },
  { slug: 'private-security', summary: 'Guarding, executive protection and security operations' },
  { slug: 'funeral-services', summary: 'Funeral direction, embalming, cemeteries and cremation' },
  { slug: 'childcare-family-services', summary: 'Childcare centers, nannies, family support' },
  { slug: 'film-tv-production', summary: 'Development, production, post and distribution' },
  { slug: 'music-industry', summary: 'Labels, publishing, royalties, live music and artist services' },
  { slug: 'book-publishing', summary: 'Editorial, production, rights and book marketing' },
  { slug: 'advertising-agencies', summary: 'Account, creative, media planning and ad operations' },
  { slug: 'broadcasting', summary: 'Radio, TV stations, broadcast engineering and news ops' },
  { slug: 'animation-vfx', summary: 'Animation, visual effects and motion capture' },
  { slug: 'photography-imaging', summary: 'Commercial, editorial and forensic photography' },
  { slug: 'creator-economy', summary: 'Creators, streaming, talent management and brand deals' },
  { slug: 'architecture-practice', summary: 'Architectural design, documentation and practice management' },
  { slug: 'higher-ed-administration', summary: 'Enrollment, student affairs, academic affairs and advancement' },
  { slug: 'k12-specialists', summary: 'Reading, math, behavior, speech and school support specialists' },
  { slug: 'edtech', summary: 'Learning products, assessment and education data' },
  { slug: 'libraries-archives', summary: 'Librarians, archivists, records and digital preservation' },
  { slug: 'research-administration', summary: 'Sponsored programs, tech transfer and research compliance' },
  { slug: 'testing-assessment', summary: 'Psychometrics, test development and credentialing' },
  { slug: 'museums-cultural-heritage', summary: 'Collections, exhibitions, heritage and historic preservation' },
  { slug: 'nonprofit-management', summary: 'Nonprofit leadership, programs, operations and volunteers' },
  { slug: 'philanthropy-fundraising', summary: 'Development, major gifts, foundations and grantmaking' },
  { slug: 'international-development', summary: 'Humanitarian aid, development programs and M&E' },
  { slug: 'advocacy-organizing', summary: 'Campaigns, community organizing and labor organizing' },
  { slug: 'faith-organizations', summary: 'Clergy, chaplaincy, ministry and faith-based operations' },
  { slug: 'housing-homelessness', summary: 'Affordable housing, shelters and homeless services' },
  { slug: 'livestock-animal-science', summary: 'Animal nutrition, breeding, dairy and animal health ops' },
  { slug: 'aquaculture-fisheries', summary: 'Fish farming, fisheries management and seafood processing' },
  { slug: 'agtech-precision-ag', summary: 'Precision agriculture, agronomy tech and farm data' },
  { slug: 'food-safety-inspection', summary: 'Food safety, HACCP, inspection and recall management' },
  { slug: 'wine-beer-spirits', summary: 'Viticulture, winemaking, brewing and distilling' },
  { slug: 'specialty-crops-horticulture', summary: 'Greenhouse, nursery, orchards and specialty crops' },
  { slug: 'culinary-product-development', summary: 'R&D chefs, flavor, sensory and food product development' },
  { slug: 'earth-atmospheric-science', summary: 'Meteorology, atmospheric and climate science' },
  { slug: 'space-science', summary: 'Planetary science, astrophysics missions and space instruments' },
  { slug: 'chemistry-rd', summary: 'Industrial chemistry R&D, analytical services and scale-up' },
  { slug: 'archaeology-heritage-science', summary: 'Archaeology, conservation science and cultural resources' },
  { slug: 'mathematics-statistics', summary: 'Applied mathematics, biostatistics and statistical consulting' },
  { slug: 'neuroscience-psychology', summary: 'Research psychology, neuroscience and human factors' },
  { slug: 'forensic-science', summary: 'Crime lab disciplines, digital forensics and forensic medicine' },
  { slug: 'laboratory-operations', summary: 'Lab automation, biorepositories, EHS and core facilities' },
  { slug: 'labor-relations-unions', summary: 'Union representation, bargaining and labor relations' },
  { slug: 'occupational-safety', summary: 'Safety management, industrial hygiene and ergonomics' },
  { slug: 'workforce-development', summary: 'Apprenticeship, job training and career services' },
  { slug: 'staffing-recruiting-agencies', summary: 'Staffing firms, executive search and RPO' },
  { slug: 'benefits-retirement', summary: 'Retirement plans, benefits consulting and pension administration' },
  { slug: 'translation-interpretation', summary: 'Medical, legal, conference and sign-language interpreting' },
];

export const CATEGORY_SLUGS: string[] = CATEGORIES.map((c) => c.slug);
export const OVERSEER_CATEGORY = 'overseer';
